"""add administration route to vaccine

Revision ID: 33b75965dcf7
Revises: e9f3d098ebe0
Create Date: 2025-11-26 09:04:28.620775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b75965dcf7'
down_revision: Union[str, None] = 'e9f3d098ebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccines', sa.Column('administration_route', sa.String(20), server_default='INJECTION', nullable=True, comment='接种途径：INJECTION(注射)/ORAL(口服)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccines', 'administration_route')
    # ### end Alembic commands ###
