"""test

Revision ID: c9e0005142cf
Revises: d9cfffe1763c
Create Date: 2025-11-09 22:17:50.743298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9e0005142cf'
down_revision: Union[str, None] = 'd9cfffe1763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_baby_id', table_name='invitations')
    op.drop_index('idx_created_by', table_name='invitations')
    op.drop_index('idx_status_expire', table_name='invitations')
    op.drop_index('uk_invite_code', table_name='invitations')
    op.drop_table('invitations')
    op.alter_column('babies', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_comment='性别',
               existing_server_default=sa.text("'unknown'"))
    op.drop_index('idx_created_by', table_name='babies')
    op.create_index(op.f('ix_babies_id'), 'babies', ['id'], unique=False)
    op.drop_table_comment(
        'babies',
        existing_comment='宝宝信息表',
        schema=None
    )
    op.alter_column('baby_family', 'relation',
               existing_type=mysql.ENUM('mom', 'dad', 'grandpa_p', 'grandma_p', 'grandpa_m', 'grandma_m', 'other', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               comment='关系(爸爸/妈妈/爷爷/奶奶等)',
               existing_comment='关系: mom-妈妈, dad-爸爸, grandpa_p-爷爷, grandma_p-奶奶, grandpa_m-外公, grandma_m-外婆, other-其他',
               existing_nullable=True)
    op.alter_column('baby_family', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_comment='是否为管理员(0否1是)',
               existing_server_default=sa.text("'0'"))
    op.drop_index('idx_baby_relation', table_name='baby_family')
    op.drop_index('idx_user_id', table_name='baby_family')
    op.drop_index('uk_baby_user', table_name='baby_family')
    op.create_index('idx_baby_user', 'baby_family', ['baby_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_baby_family_id'), 'baby_family', ['id'], unique=False)
    op.drop_table_comment(
        'baby_family',
        existing_comment='宝宝-家庭成员关系表',
        schema=None
    )
    op.drop_column('baby_family', 'joined_at')
    op.drop_column('baby_family', 'relation_display')
    op.drop_column('baby_family', 'updated_at')
    op.drop_index('idx_user_id', table_name='diaper_records')
    op.create_index(op.f('ix_diaper_records_baby_id'), 'diaper_records', ['baby_id'], unique=False)
    op.create_index(op.f('ix_diaper_records_id'), 'diaper_records', ['id'], unique=False)
    op.drop_table_comment(
        'diaper_records',
        existing_comment='排便/排尿记录表',
        schema=None
    )
    op.drop_index('idx_user_id', table_name='feeding_records')
    op.create_index(op.f('ix_feeding_records_baby_id'), 'feeding_records', ['baby_id'], unique=False)
    op.create_index(op.f('ix_feeding_records_id'), 'feeding_records', ['id'], unique=False)
    op.drop_table_comment(
        'feeding_records',
        existing_comment='喂养记录表',
        schema=None
    )
    op.drop_index('idx_user_id', table_name='growth_records')
    op.create_index(op.f('ix_growth_records_baby_id'), 'growth_records', ['baby_id'], unique=False)
    op.create_index(op.f('ix_growth_records_id'), 'growth_records', ['id'], unique=False)
    op.drop_table_comment(
        'growth_records',
        existing_comment='生长发育记录表',
        schema=None
    )
    op.alter_column('sleep_records', 'wake_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='夜醒次数',
               existing_server_default=sa.text("'0'"))
    op.drop_index('idx_user_id', table_name='sleep_records')
    op.create_index(op.f('ix_sleep_records_baby_id'), 'sleep_records', ['baby_id'], unique=False)
    op.create_index(op.f('ix_sleep_records_id'), 'sleep_records', ['id'], unique=False)
    op.drop_table_comment(
        'sleep_records',
        existing_comment='睡眠记录表',
        schema=None
    )
    op.drop_index('idx_openid', table_name='users')
    op.drop_index('uk_openid', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('uk_openid', 'users', ['openid'], unique=True)
    op.create_index('idx_openid', 'users', ['openid'], unique=False)
    op.create_table_comment(
        'sleep_records',
        '睡眠记录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_sleep_records_id'), table_name='sleep_records')
    op.drop_index(op.f('ix_sleep_records_baby_id'), table_name='sleep_records')
    op.create_index('idx_user_id', 'sleep_records', ['user_id'], unique=False)
    op.alter_column('sleep_records', 'wake_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='夜醒次数',
               existing_server_default=sa.text("'0'"))
    op.create_table_comment(
        'growth_records',
        '生长发育记录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_growth_records_id'), table_name='growth_records')
    op.drop_index(op.f('ix_growth_records_baby_id'), table_name='growth_records')
    op.create_index('idx_user_id', 'growth_records', ['user_id'], unique=False)
    op.create_table_comment(
        'feeding_records',
        '喂养记录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_feeding_records_id'), table_name='feeding_records')
    op.drop_index(op.f('ix_feeding_records_baby_id'), table_name='feeding_records')
    op.create_index('idx_user_id', 'feeding_records', ['user_id'], unique=False)
    op.create_table_comment(
        'diaper_records',
        '排便/排尿记录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_diaper_records_id'), table_name='diaper_records')
    op.drop_index(op.f('ix_diaper_records_baby_id'), table_name='diaper_records')
    op.create_index('idx_user_id', 'diaper_records', ['user_id'], unique=False)
    op.add_column('baby_family', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.add_column('baby_family', sa.Column('relation_display', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='角色显示名称（用于自定义角色或特殊称呼）'))
    op.add_column('baby_family', sa.Column('joined_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='加入时间'))
    op.create_table_comment(
        'baby_family',
        '宝宝-家庭成员关系表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_baby_family_id'), table_name='baby_family')
    op.drop_index('idx_baby_user', table_name='baby_family')
    op.create_index('uk_baby_user', 'baby_family', ['baby_id', 'user_id'], unique=True)
    op.create_index('idx_user_id', 'baby_family', ['user_id'], unique=False)
    op.create_index('idx_baby_relation', 'baby_family', ['baby_id', 'relation'], unique=False)
    op.alter_column('baby_family', 'is_admin',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否为管理员(0否1是)',
               existing_server_default=sa.text("'0'"))
    op.alter_column('baby_family', 'relation',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('mom', 'dad', 'grandpa_p', 'grandma_p', 'grandpa_m', 'grandma_m', 'other', collation='utf8mb4_unicode_ci'),
               comment='关系: mom-妈妈, dad-爸爸, grandpa_p-爷爷, grandma_p-奶奶, grandpa_m-外公, grandma_m-外婆, other-其他',
               existing_comment='关系(爸爸/妈妈/爷爷/奶奶等)',
               existing_nullable=True)
    op.create_table_comment(
        'babies',
        '宝宝信息表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_babies_id'), table_name='babies')
    op.create_index('idx_created_by', 'babies', ['created_by'], unique=False)
    op.alter_column('babies', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_comment='性别',
               existing_server_default=sa.text("'unknown'"))
    op.create_table('invitations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='邀请ID'),
    sa.Column('baby_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='宝宝ID'),
    sa.Column('invite_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='邀请码（加密字符串）'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人用户ID'),
    sa.Column('expire_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='过期时间'),
    sa.Column('status', mysql.ENUM('active', 'expired', 'used'), server_default=sa.text("'active'"), nullable=False, comment='状态: active-有效, expired-已过期, used-已使用'),
    sa.Column('used_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='使用者用户ID'),
    sa.Column('used_at', mysql.TIMESTAMP(), nullable=True, comment='使用时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name='fk_invitation_baby', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_invitation_creator'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name='fk_invitation_user'),
    sa.PrimaryKeyConstraint('id'),
    comment='家庭邀请表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='家庭邀请表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_invite_code', 'invitations', ['invite_code'], unique=True)
    op.create_index('idx_status_expire', 'invitations', ['status', 'expire_at'], unique=False)
    op.create_index('idx_created_by', 'invitations', ['created_by'], unique=False)
    op.create_index('idx_baby_id', 'invitations', ['baby_id'], unique=False)
    # ### end Alembic commands ###
