"""add vaccine detail fields

Revision ID: e9f3d098ebe0
Revises: ff00aa11bb22
Create Date: 2025-11-25 10:49:08.697218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f3d098ebe0'
down_revision: Union[str, None] = 'ff00aa11bb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccines', sa.Column('side_effects', sa.Text(), nullable=True, comment='常见副作用'))
    op.add_column('vaccines', sa.Column('precautions', sa.Text(), nullable=True, comment='注意事项'))
    op.add_column('vaccines', sa.Column('contraindications', sa.Text(), nullable=True, comment='禁忌症'))
    op.add_column('vaccines', sa.Column('interval_info', sa.Text(), nullable=True, comment='接种间隔说明'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccines', 'interval_info')
    op.drop_column('vaccines', 'contraindications')
    op.drop_column('vaccines', 'precautions')
    op.drop_column('vaccines', 'side_effects')
    # ### end Alembic commands ###
